# Generated by Django 3.2.12 on 2024-11-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add a new book'), ('can_change_book', 'can change a book'), ('can_delete_book', 'can delete a book')]},
        ),
    ]
